# Links on sidebar
menu:
  Home: /
  # Tags: /tags/
  # Categories: /categories/
  About: /about/
  Projects: /archives/

# Pictures shown on the sidebar
# Use the absolute URL after generating
avatar: /assets/logo.jpg
sidebar_background: /assets/back.jpg

rss: /atom.xml

# Content
excerpt: true
excerpt_link: Read On »

# Will be shown on the bottom.
## To add new icon, just copy .svg to source/assets/ and add entries below.
media:
  github: https://github.com/lizihan021
  # facebook: https://www.facebook.com/profile.php?id=100004252391322
  linkedin: https://www.linkedin.com/in/zihan-li-927ba5126/
source_han_font: true

# Disqus settings
disqus:
  # 'disabled' | 'all' | 'post'
  enable: disabled
  # Shortname of your disqus website.
  # See disqus admin
  shortname:

# Miscellaneous
favicon: /favicon.png
